config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  concern :purgable do
    delete :index, :on => :collection, :action => :purge, :as => :purge
  end

  resource  :home 
  resource  :try_it do
    get :source, :as => :source
  end
  resources :mappings, :concerns => :purgable
  resources :good_phrases, :concerns => :purgable
  resources :bad_phrases, :concerns => :purgable
  resources :polite_suggestions do
    post :batch_create, :on => :collection, :action => :batch_create, :as => :batch_create
  end

  root :controller => 'homes', :action => 'show'
  
end

app/models/mapping.rb
class Mapping < ActiveRecord::Base
  belongs_to :good_phrase, :foreign_key => 'good_phrase_id', :class_name => 'Phrase'
  belongs_to :bad_phrase, :foreign_key => 'bad_phrase_id', :class_name => 'Phrase'

  validates_uniqueness_of :good_phrase_id, :scope => :bad_phrase_id
  #scope(:alphabetical, -> { order 'dp_categories.name ASC' })

  scope(:desc_bad_word_count, -> { includes(:bad_phrase).order("word_count DESC").references(:bad_phrase) })
end

app/models/phrase.rb
class Phrase < ActiveRecord::Base
  has_many :bad_mappings, :foreign_key => 'bad_phrase_id', :class_name => 'Mapping', :dependent => :destroy
  has_many :good_mappings, :foreign_key => 'good_phrase_id', :class_name => 'Mapping', :dependent => :destroy

  validates_presence_of :value
  validates_uniqueness_of :value#, :scope => [:positive_sentiment]

  before_save :set_word_count

  scope(:positive, -> { where "phrases.positive_sentiment = true" })
  scope(:negative, -> { where "phrases.positive_sentiment = false" })
  scope(:alphabetical, -> { order 'phrases.value ASC' })
  scope(:desc_word_count, -> { order "word_count DESC" })

  private

  def set_word_count
    self.word_count = self.value.count(" ") + 1
  end
end

app/models/polite_suggestion.rb
class PoliteSuggestion < Phrase
  default_scope(-> { where('phrases.positive_sentiment = false').includes(:bad_mappings).where('mappings.id is null').references(:mappings) } )
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_uniqueness_of :email
  validates_presence_of :email

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def authenticate_admin!
    unless current_user.try(:admin?).present?
      flash[:notice] = 'Pardon us, but we don\'t believe you should be going there'
      redirect_to root_path and return false
    end
  end
end

app/controllers/bad_phrases_controller.rb
class BadPhrasesController < ApplicationController
  before_filter :authenticate_admin!, :only => :purge

  def index
    @bad_phrases = Phrase.negative.all
  end

  def new
    @bad_phrase = Phrase.new
  end

  def create
    begin
      bad_phrase  = Phrase.where(:value => params[:bad_phrase][:value], :positive_sentiment => false).first_or_create!
      flash[:success] = "Your contribution has been noted, and we thank you for your assitance in the endevaor"
      redirect_to new_bad_phrase_path
    rescue Exception => error
      @bad_phrase = Phrase.new
      flash[:error] = "Do pardon us, but #{error}"
      render :action => :new
    end
  end

  def purge
    Phrase.where(:id => params[:ids]).destroy_all
    flash[:success] = 'Those pesky things shan\'t be disturbing you any more'
    redirect_to bad_phrases_path
  end
end

app/controllers/good_phrases_controller.rb
class GoodPhrasesController < ApplicationController
  before_filter :authenticate_admin!, :only => :purge

  def index
    @good_phrases = Phrase.positive.all
  end
  
  def purge
    Phrase.where(:id => params[:ids]).destroy_all
    flash[:success] = 'Those pesky things shan\'t be disturbing you any more'
    redirect_to good_phrases_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
    @mapping  = Mapping.new
    @mappings = Mapping.all
  end
end

app/controllers/mappings_controller.rb
class MappingsController < ApplicationController
  before_filter :authenticate_admin!, :only => :purge

  def index
    @mappings = Mapping.all
  end

  def new
    @mapping = Mapping.new
  end

  def create
    begin
      bad_phrase  = Phrase.where(:value => params[:mapping][:bad_phrase], :positive_sentiment => false).first_or_create!
      good_phrase = Phrase.where(:value => params[:mapping][:good_phrase], :positive_sentiment => true).first_or_create!
      mapping     = Mapping.create! :bad_phrase_id => bad_phrase.id, :good_phrase_id => good_phrase.id 
      flash[:success] = "Your contribution has been noted, and we thank you for your assitance in the endevaor"
      redirect_to params[:back_to] || root_path
    rescue Exception => error
      @mapping = Mapping.new
      flash[:error] = "Do pardon us, but #{error}"
      if params[:back_to] == "/"
        redirect_to root_path
      else
        render :action => :new
      end
    end
  end

  def purge
    Mapping.where(:id => params[:ids]).destroy_all
    flash[:success] = 'Those pesky things shan\'t be disturbing you any more'
    redirect_to mappings_path
  end

end

app/controllers/polite_suggestions_controller.rb
class PoliteSuggestionsController < ApplicationController

  def index
    @polite_suggestions = PoliteSuggestion.all
  end


  def batch_create
    begin
      mappings = params[:mappings].collect do |mapping|
        next if mapping[:good_phrase].blank?
        good_phrase = Phrase.where(:value => mapping[:good_phrase], :positive_sentiment => true).first_or_create!
        mapping     = Mapping.create! :bad_phrase_id => mapping[:bad_phrase_id], :good_phrase_id => good_phrase.id 
      end

      if mappings.compact.present?
        flash[:success] = "Your contribution has been noted, and we thank you for your assitance in the endevaor"
      end
      redirect_to polite_suggestions_path
    rescue Exception => error
      @polite_suggestions = PoliteSuggestion.all
      flash[:error] = "Do pardon us, but #{error}"
      render :action => :index
    end
  end
end

app/controllers/try_its_controller.rb
class TryItsController < ApplicationController

  before_filter :grab_url

  def create
    render :action => :show
  end

  def show
  end

  def source
#      @source = Premailer.new(@url, :warn_level => Premailer::Warnings::SAFE)

#     @source  = Roadie::Document.new(RestClient.get(@url)).transform
#     document  = Roadie::Document.new(RestClient.get(@url).to_s)
#     uri_data = URI.parse(@url)
#     #document.url_options = { :host => uri_data.host, :protocol => uri_data.scheme }
#     @source = document.transform
# 
#  
#     result = @source.to_inline_css
#     render :text => result

    begin
      raw_source = RestClient.get(@url)
      document   = Roadie::Document.new(RestClient.get(@url).to_s)
      uri_data   = URI.parse(@url)
      #document.url_options = { :host => uri_data.host, :protocol => uri_data.scheme }
      @source    = document.transform
    rescue Exception => e
      @source    = raw_source
    end
    render :text => @source
  end

  private

  def grab_url
    @url = params[:url] || params[:try_it_url]
    @url = "http://#{@url}" unless @url =~ URI::regexp
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def punish_bad_word(string)
    content_tag(:span, :class => 'bad_word_wrapper') do
      content_tag(:span, :class => 'bad_word_heart') do
        string.split(//).join("\u2063")
      end
    end
  end

  def obfuscate(string)
    string.split(//).join("\u2063")
  end

end

app/helpers/bad_phrases_helper.rb
module BadPhrasesHelper
end

app/helpers/good_phrases_helper.rb
module GoodPhrasesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/mappings_helper.rb
module MappingsHelper
end

app/helpers/polite_suggestions_helper.rb
module PoliteSuggestionsHelper
end

app/helpers/try_its_helper.rb
module TryItsHelper
end

app/views/admin/mappings/index.html.erb
<ul>Mappings
  <%= form_tag purge_admin_mappings_path do %>
    <% @mappings.each do |mapping| %>
      <li>
        <%= check_box_tag 'ids[]', mapping.id %>
        <%= mapping.bad_phrase.value %> => <%= mapping.good_phrase.value %>
      </li>
    <% end %>
    <%= submit_tag 'purge!!' %>
  <% end %>
</ul>

app/views/bad_phrases/index.html.erb
<ul>Bad Phrases
  <% @bad_phrases.all.each do |bad_phrase| %>
    <li><%= punish_bad_word(bad_phrase.value) %></li>
  <% end %>
</ul>

app/views/bad_phrases/new.html.erb
<%= form_for :bad_phrase, :as => :post, :url => bad_phrases_path do |f| %>
  <div>
    <%= f.label :value, 'Bad Prase' %>
    <%= f.text_field :value %>
  </div>
  <%= f.submit %>
<% end %>

app/views/good_phrases/index.html.erb
<ul>Good Phrases
  <% @good_phrases.all.each do |good_phrase| %>
    <li><%= good_phrase.value %></li>
  <% end %>
</ul>

app/views/homes/show.html.erb
<div id="wrapper">
<div id="header">
  <ul id="navigation">
    <li><%= link_to "Try It Out", "#try-it-out" %></li>
    <li><%= link_to "How It works", "#how-it-works" %></li>
    <li><%= link_to "Contribute", "#contribute" %></li>
    <li><%= link_to "Submissions", "#submissions" %></li>
    <li><%= link_to "About", "#about" %></li>
<!--     <li><%= link_to "Press", "#press" %></li> -->
  </ul>
  <div style="clear:both"></div>
  <div id="title-area">
    <%= link_to "install plugin", "javascript:void(0)", :id => "install-plugin" %>
    <div id="title"><span class="red-dotted-underline">Internetiquette</span></div>
    <div id="tagline">Making the internet more polite, one line at a time.</div>
  </div>
  <div style="clear:both"></div>
</div>
<div id="body">
  <div class="row try-it-out">
    <div class="center">
      <div class="caption">
        <h2><a name="try-it-out">Try It Out:</a></h2>
      </div>
      <div class="other">
        <%= form_tag try_it_path, :id => 'try_it_form' do |f| %>
          <%= text_field_tag :try_it_url, nil, :placeholder => "Enter URL for the rudest site you can think of" %>
          <%= hidden_field_tag :back_to, request.fullpath %>
          <%= link_to "Clean it up", "javascript:void(0)", :class => "submit", :onclick => '$("form#try_it_form").submit()' %>
          <%#= f.submit "Submit", :class => "submit" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row how-it-works">
    <div class="step intro">
      <div class="step-header">
        <a name="how-it-works">How It works:</a>
      </div>
      <div class="step-body">
        Internetiquette is a browser plugin that converts internet rudeness to into polite statements.<br/> Crowd-sourced submissions.
      </div>
    </div>
    <div class="step">
      <div class="step-header">Enable Extension</div>
      <div class="step-body">
        <%= image_tag 'circlePlaceholder.png' %>
      </div>
    </div>
    <div class="step">
      <div class="step-header visit-any-site">Visit any site</div>
      <div class="step-body">
        <%= image_tag 'circlePlaceholder.png' %>
      </div>
    </div>
    <div class="step">
      <div class="step-header">Marvel at Politeness</div>
      <div class="step-body">
        <%= image_tag 'circlePlaceholder.png' %>
      </div>
    </div>

  </div>
  <div class="row contribute">
    <div class="center">
      <div class="caption">
        <h2><a name="contribute">Contribute:</a></h2>
      </div>
      <div class="other">
        <%= form_for @mapping do |f| %>
          <%= f.text_field :bad_phrase, :placeholder => "Rude Phrase" %>
          <%= f.text_field :good_phrase, :placeholder => "Polite Suggestion" %>
          <%= hidden_field_tag :back_to, request.fullpath %>
          <%= link_to "submit", "javascript:void(0)", :class => "submit", :onclick => '$("form#new_mapping").submit()' %>
          <%#= f.submit "Submit", :class => "submit" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row submissions">
    <div class="caption">
      <h2><a name="submissions">Submissions:</a></h2>
      <%= @mappings.count %> and counting
    </div>
    <div class="other">
      <dl id="submissions_list">
        <% @mappings.each do |mapping| %>
          <dt><%= obfuscate mapping.bad_phrase.value %></dt>
          <dd><%= mapping.good_phrase.value %></dd>
        <% end %>
      </ul>
    </div>
  </div>
  </div>
</div>
<div id="buffer"></div>
<div id="footer-frame">
  <div id="footer-wrapper">
    <div id="footer-body">
      <div class="row about">
        <div class="caption">
          <h2><a name="about">About<br/>The Project</a></h2>
        </div>
        <div class="other">
          <div class="content">
            Internetiquette is a weekend project done by <%= link_to "Charles", "https://twitter.com/rkjiii" %> and Magnus at HQ, Brooklyn and is inspired by the idea that the internet needn't bring out the worst in all of us.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--
  <div class="row press">
   <div class="press">
    <h2><a name="press">Press</a></h2>
  </div>
  <div class="press">
    <div>
      <p>
        Suspendisse non commodo elit, a convallis libero. Nam porta, justo et convallis sagittis, arcu ante porttitor mauris, nec feugiat mi orci elementum
      </p>
      <div>- Jesse Lochrie</div>
    </div>
  </div> </div>-->

app/views/layouts/_flash.html.erb
<% flash.each do |name, message| %>
  <% if message.is_a?(String) %>
    
      <%= name %>: <%= message %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<dl>
  <%= link_to 'home', root_path %>
  <% if user_signed_in? %>
    welcome <%= current_user.email %>
    <%= '(ADMIN)' if current_user.admin? %>,
    <%= link_to 'sign out', destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to 'log in', new_user_session_path %>
    <%= link_to 'sign up', new_user_registration_path %>
  <% end %>
  
  <dt>Mappings:</dt>
  <dd><%= link_to 'new', new_mapping_path %> <%= link_to 'list', mappings_path %></dd>
  <dt>Bad Phrases:</dt>
  <dd><%= link_to 'new', new_bad_phrase_path %> <%= link_to 'list', bad_phrases_path %></dd>
  <dt>Good Phrases:</dt>
  <dd><%= link_to 'list', good_phrases_path %></dd>
  <dt><%= link_to 'suggestions', polite_suggestions_path %></dd>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Internetiquette</title>
  <%= stylesheet_link_tag    'application', :media => 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <script>
    /* Run any additional JS provided by the template */
    <%= yield :js %>
  </script>
</head>
<body id="<%= controller.controller_name.singularize %>">
  
  <%= render :partial => '/layouts/navigation' unless ['home', 'try_it'].include? controller.controller_name.singularize %>
  <%= render :partial => '/layouts/flash' %>
  <%= yield %>

</body>
</html>

app/views/mappings/_list.html.erb
<% @mappings.each do |mapping| %>
  <li>
    <%= check_box_tag 'ids[]', mapping.id if current_user.try(:admin?) %>
    <%= punish_bad_word(mapping.bad_phrase.value) %> => <%= mapping.good_phrase.value %>
  </li>
<% end %>

app/views/mappings/index.html.erb
<ul>Mappings
  <% if current_user.try(:admin?) %>
    <%= form_tag purge_mappings_path do %>
      <%= render :partial => 'list' %>
      <%= submit_tag 'purge!!' %>
    <% end %>
  <% else %>
    <%= render :partial => 'list' %>
  <% end %>
</ul>

app/views/mappings/new.html.erb
<%= form_for @mapping do |f| %>

  <div>
    <%= f.label :bad_phrase, 'Bad Phrase' %>
    <%= f.text_field :bad_phrase %>
  </div>

  <div>
    <%= f.label :good_phrase, 'Good Phrase' %>
    <%= f.text_field :good_phrase %>
  </div>
  <%= f.submit %>
<% end %>

app/views/polite_suggestions/index.html.erb
<% content_for :head do %>
  <style type="text/css">
    .box_with_border {
      width: 100px;
      display: inline-block;
      border: 1px solid black;
    }
  </style>
<% end %>


<ul>Suggestion
  <%= form_tag batch_create_polite_suggestions_path do %>
    <% @polite_suggestions.each do |polite_suggestion| %>
      <li>
        <span class="box_with_border">
          <%= punish_bad_word(polite_suggestion.value) %>
        </span>
        =>
        <%= hidden_field_tag 'mappings[][bad_phrase_id]', polite_suggestion.id %>
        <%= text_field_tag 'mappings[][good_phrase]' %>
      </li>
    <% end %>
    <%= submit_tag 'batch create' %>
  <% end %>
</ul>

app/views/try_its/show.html.erb
<% content_for :js do %>
  function resizeIframe_and_clean(obj) {
    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
    document.getElementById('try-it-example').contentWindow.clean = window.clean;
    document.getElementById('try-it-example').contentWindow.clean();
    $("#island .toggable").toggle();
  }

  function clean() {
    request = new XMLHttpRequest();
    request.open('GET', 'http://internetiquette.herokuapp.com/mappings.json', true);

    request.onload = function() {
      if (request.status >= 200 && request.status < 400){
        // Success!
        window.data = JSON.parse(request.responseText);
        for (bad_phrase in window.data.mappings) {
          console.log("replacing "+ bad_phrase);
          var regex = new RegExp(bad_phrase,"ig");
          findAndReplaceDOMText(document.getElementById('try-it-example').contentDocument.getElementsByTagName("body")[0], {
           find: regex,
           replace: window.data.mappings[bad_phrase].toUpperCase()
          });
        }
      } else {
        // We reached our target server, but it returned an error
        console.log("failure")
      }
    };

    request.onerror = function() {
      // There was a connection error of some sort
    };

    request.send();
  }
<% end %>

<div id="island">
  <h2>
    <%= link_to "<- Back to Internetiquette", root_path %>
  </h2>
  <br/>
  <span>
    <span class="toggable" style="display:none">
      Finished:
    </span>
    <span class="toggable">
      Loading: 
    </span>
   <%= link_to @url, @url %>  <%#(the preview may mess things up)%></span>
</div>
<iframe id="try-it-example" src="<%= source_try_it_path(:url => @url) %>" frameBorder="0" height="1000px" width="100%" onload='javascript:resizeIframe_and_clean(this);'>
</iframe>

app/views/try_its/source.html.erb
<%= raw(@source) %>